# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "JSDay Maceió 2015"
email: "hey@caravanaweb.com.br"
description: "O JSday é um evento imersivo focado em Javascript e tudo o que essa linguagem tem a oferecer"
baseurl: ""
url: "http://jsday.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-62574701-1"
googleAnalyticsSiteUrl: "jsday.com.br"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Caravana Web"
# organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Comunidade com o intuito de proporcionar a disseminação do conhecimento relacionado à Tecnologia e Web"
organizerEmail: "hey@caravanaweb.com.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://fb.com/caravanaweb"

# Head
metaKeywords: "event, javascript, js, angularjs, google maps, ionic, firebase, aplicativos híbridos"
twitterAccount: "@frontinmaceio"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "mailto:hey@caravanaweb.com.br?subject=Patrocínio JSday Maceió 2015"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "JS Experts"}
 - {permalink: "/js4girls/", text: "JS4Girls"}
bottomNavigationLinks:
 - {link: "http://even.tc/jsday-maceio-2015", text: "Vem codificar conosco! </>"}
rightNavigationButtons:
 - {link: "http://even.tc/jsday-maceio-2015", text: "Vem codificar conosco! </>"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "JSday Maceió: <typeout>"
eventDate: "12 de Setembro, 2015"
typeoutTextValues: '"", "JavaScript", "AngularJS", "Ionic SDK", "Google Maps API"'
typeoutFallback: "JavaScript"
heroButtons:
 - {link: "http://even.tc/jsday-maceio-2015", text: "Garanta sua vaga, inscreva-se!"}

# About Block
aboutTitle: "Sobre o JSday Maceió"
aboutBlock:
 - {title: "Javascript", image: "javascript.jpg", text: "Como uma das linguagens mais populares e mais utilizadas atualmente, você pode encontrá-la no seu navegador, no seu smartphone e até em sua geladeira, seguindo o conceito de Internet das Coisas." }
 - {title: "Mercado", image: "office.jpg", text: "O mercado tem uma demanda gigantesca por profissionais que conhecem as nuances do Javascript e estejam por dentro das novidades do ES6" }
 - {title: "Networking", image: "networking.jpg", text: "Uma das melhores formas para desenvolvimento profissional com certeza é conhecer a comunidade que você faz parte" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "participantes", detail: ""}
 - {count: "8", specialCharacter: "+", info: "horas", detail: "de puro código"}
 - {count: "8", specialCharacter: "+", info: "palestrantes", detail: "com tópicos incríveis"}
 - {count: "1", specialCharacter: "", info: "trilha", detail: "foco total em JavaScript"}

# Latest News Block
latestNewsTitle: "Novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "JavaScript Experts"
rockstarSpeakersButtonText: "Conheça todos Palestrantes"

# Location Block
locationBlockTitle: "Local"
eventLocationName: "Auditório CESMAC"
eventLocationLink: "http://cesmac.com.br"
eventStreetAddress: "R. Cônego Machado, 918 - Farol"
eventAddressLocality: "Maceió"
eventAddressLocalityRegion: "AL"
eventPostalCode: "57051-160"
eventAddressCountry: "Brasil"
eventStartTime: "2015-09-12T08:00"
eventDoorTime: "09:00"
eventEndTime: "2015-09-12T17:00"
eventPlaceCoordinates: "-9.655388, -35.737538"
mapCenterCoordinates: "-9.655388, -35.737538"
mapMobileCenterCoordinates: "-9.655388, -35.737538"

# Venue Block
venueBlockTitle: "Local"
venueTitle: "CESMAC Auditório"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "JavaScript? YEAH!"
twitterHashTag: "jsdaymaceio"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Ajude-nos a codificar. Patrocine!"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Inscreva-se.now()"
ticketsOffers:
 -
  name: "JS4Girls"
  price: ""
  priceCurrency: "Gratuito"
  buyButtonLink: "http://even.tc/jsday-maceio-2015"
  buyButtonText: "{{Participar}}"
  validFrom: "2015-08-21T10:00"
  validThrough: "2015-09-11T23:59"
 -
  name: "1º lote: JS #ftw"
  price: "25"
  priceCurrency: "R$"
  buyButtonLink: "http://even.tc/jsday-maceio-2015"
  buyButtonText: "{{Comprar}}"
  validFrom: "2015-08-21T10:00"
  validThrough: "2015-09-06T23:59"
 -
  name: "2º Lote: ES6"
  price: "45"
  priceCurrency: "R$"
  buyButtonLink: "http://even.tc/jsday-maceio-2015"
  buyButtonText: "{{Última change! Comprar agora}}"
  validFrom: "2015-09-07T00:00"
  validThrough: "2015-09-11T23:59"
  disabled: true

# Footer
socialLinks:
 - {link: "https://plus.google.com/+GdgmaceioRocksIt", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=frontinmaceio", icon: "twitter"}
 - {link: "https://facebook.com/FrontinMaceio", icon: "facebook"}

footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://frontinamceio.com.br", text: "Front in Maceió"}
   - {link: "http://fb.com/caravanaweb", text: "Caravana Web"}
   - {link: "http://gdgmaceio.rocks", text: "GDG Maceió"}
   - {link: "https://developers.google.com/groups/?hl=pt-br", text: "Google Developers"}
 -
  title: "Contato"
  links:
   - {link: "mailto:hey@caravanaweb.com.br", text: "hey@caravanaweb.com.br"}
 -
  title: "FAQ"
  links:
   - {link: "http://pt-br.confcodeofconduct.com/", text: "Código de Conduta"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Call for Papers
cfpTitle: "Espalhe o amor pelo JavaScript"
cfpDescription: "Uma oportunidade excelente para você mostrar do que o JavaScript é capaz, você já está por dentro das novidades do ES6, sabe como ninguém utilizar os componentes do ReactJS, programa usando JavaScript Funcional ou ainda quer explicar do que se trata esse tal de BabelJS. Siga os passos abaixo e envie sua proposta."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

#JS4Girls
js4girlsTitle: "JS4Girls"
trainingImage: "womentechmakers.jpg"
trainingTitle: "Instrutora"
js4girlsRows:
 - {title: "Workshop Gratuito para mulheres", image: "1.png", details: "O JS4Girls é uma iniciativa gratuita que tem como objetivo ensinar JavaScript para mulheres através da promoção de um ambiente exclusivamente feminino. As mesmas meninas que participarem do JS4Girls poderão assistir as palestras da tarde do JSday e ver o quão versátil é o que elas aprenderam pela manhã.﻿"}
 - {title: "Por que JavaScript?", image: "2.png", details: "Uma das linguagens mais populares e mais utilizadas atualmente, você pode encontrá-la no seu navegador, no seu smartphone e até em sua geladeira, seguindo o conceito de Internet das Coisas.<br><br>Hoje o JavaScript está entrando num processo de evolução, inovação e padronização, com novos desenvolvimentos, como Node.js, permitindo usar o JavaScript no servidor, além de APIs HTML5 para obter dados sobre a localização de dispositivos e características geográficas e muito mais."}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false


# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
