# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "JSday Feira de Santana 2016"
email: "contato@jsday.com.br"
description: "O JSday é um evento imersivo focado em Javascript e tudo o que essa linguagem tem a oferecer"
baseurl: ""
url: "http://jsday.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-62574701-1"
googleAnalyticsSiteUrl: "jsday.com.br"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "JSday Feira de Santana"
# organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "O JSday é um evento imersivo focado em Javascript e tudo o que essa linguagem tem a oferecer"
organizerEmail: "contato@jsday.com.br"
# organizerLogo: "/img/seo/organizer-logo.png"
# organizerLink: "http://fb.com/caravanaweb"

# Head
metaKeywords: "event, javascript, js, angularjs, google maps, ionic, firebase, aplicativos híbridos, nodebots"
twitterAccount: "@jsdaybr"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus-fsa.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter-fsa.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook-fsa.png"

# Documents
c4pUrl: "http://goo.gl/forms/vKgUCUyE3iTJe4lo2"
c4sponsorsUrl: "mailto:contato@jsday.com.br?subject=Patrocínio JSday Feira de Santana 2016"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "JS Experts"}
 # - {permalink: "/schedule/", text: "Lineup"}
 # - {permalink: "/live/", text: "Live"}

bottomNavigationLinks:
 - {link: "http://even.tc/jsday-feira-de-santana-2016", text: "Garantir minha vaga"}
rightNavigationButtons:
 - {link: "http://even.tc/jsday-feira-de-santana-2016", text: "Garantir minha vaga"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "#JSdayFSA: <typeout>"
eventDate: "23 de Julho, 2016"
typeoutTextValues: '"", "JavaScript", "AngularJS", "Firebase", "Electron"'
typeoutFallback: "JavaScript"
heroButtons:
 - {link: "http://even.tc/jsday-feira-de-santana-2016", text: "Garantir minha vaga"}
 - {link: "http://goo.gl/forms/vKgUCUyE3iTJe4lo2", text: "Quero palestrar"}

# About Block
aboutTitle: "Sobre o JSday Feira de Santana"
aboutBlock:
 - {title: "Javascript", image: "javascript.jpg", text: "Como uma das linguagens mais populares e mais utilizadas atualmente, você pode encontrá-la no seu navegador, no seu smartphone e até em sua geladeira, seguindo o conceito de Internet das Coisas." }
 - {title: "Mercado", image: "office.jpg", text: "O mercado tem uma demanda gigantesca por profissionais que conhecem as nuances do Javascript e estejam por dentro das novidades do ES6" }
 - {title: "Networking", image: "networking.jpg", text: "Uma das melhores formas para desenvolvimento profissional com certeza é conhecer a comunidade que você faz parte" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "250", specialCharacter: "+", info: "participantes", detail: ""}
 - {count: "24", specialCharacter: "+", info: "horas", detail: "de puro código"}
 - {count: "20", specialCharacter: "+", info: "palestrantes", detail: "com tópicos incríveis"}
 - {count: "2", specialCharacter: "", info: "trilhas", detail: "foco total em JavaScript"}

# Latest News Block
latestNewsTitle: "Novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "JavaScript Experts"
rockstarSpeakersButtonText: "Conheça todos Palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "UNIFACS"
eventLocationLink: "http://www.unifacs.br/"
eventStreetAddress: "Rua Rio Tinto, 152 - Santa Mônica"
eventAddressLocality: "Feira de Santana"
eventAddressLocalityRegion: "BA"
eventPostalCode: "44077-140"
eventAddressCountry: "Brasil"
eventStartTime: "2016-07-23T08:00"
eventDoorTime: "08:00"
eventEndTime: "2016-07-23T18:00"
eventPlaceCoordinates: "-12.2585924,-38.9336747"
mapCenterCoordinates: "-12.2585924,-38.9336747"
mapMobileCenterCoordinates: "-12.2585924,-38.9336747"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "UNIFACS"
venueFeatures: ["Localizado próximo ao anel rodoviário", "Estrutura moderna e acessível", "Na Princesa do Sertão"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Tweets.get()"
twitterHashTag: "jsdayfsa"
twitterFeed: "#"

# Partners Block
organizersTitle: "Organização"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Ajude-nos a codificar. Patrocine!"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Inscreva-se.now()"
ticketsOffers:
 -
  name: "1º Lote"
  price: "60"
  priceCurrency: "R$"
  buyButtonLink: "http://even.tc/jsday-feira-de-santana-2016"
  buyButtonText: "{{Comprar}}"
  validFrom: "2016-06-04T10:00"
  validThrough: "2016-07-23T23:59"
 -
  name: "2º Lote"
  price: "80"
  priceCurrency: "R$"
  buyButtonLink: "http://even.tc/jsday-feira-de-santana-2016"
  buyButtonText: "{{Comprar}}"
  validFrom: "2016-06-04T00:00"
  validThrough: "2016-07-23T23:59"
 -
  name: "3º Lote"
  price: "100"
  priceCurrency: "R$"
  buyButtonLink: "http://even.tc/jsday-feira-de-santana-2016"
  buyButtonText: "{{Comprar}}"
  validFrom: "2016-06-04T00:00"
  validThrough: "2016-07-23T06:00"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=jsdaybr", icon: "twitter"}
 - {link: "https://www.facebook.com/jsdaybr/", icon: "facebook"}

footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://cesar.org.br", text: "C.E.S.A.R"}
   - {link: "http://cesar.edu.br", text: "CESAR.EDU"}   
   - {link: "http://fb.com/caravanaweb", text: "Caravana Web"}    
 -
  title: "Edições Anteriores"
  links:
   - {link: "http://cg.jsday.com.br", text: "JSday Campina Grande"}
   - {link: "http://mcz.jsday.com.br", text: "JSday Maceió"}
   - {permalink: "/wtm-javascript-codelab/", text: "JSday Maceió Codelab WTM JavaScript"}
   - {link: "http://fsa.jsday.com.br", text: "JSday Feira de Santana"}
 -
  title: "Contato"
  links:
   - {link: "mailto:contato@jsday.com.br", text: "contato@jsday.com.br"}
 -
  title: "FAQ"
  links:
   - {link: "http://pt-br.confcodeofconduct.com/", text: "Código de Conduta"}
   - {link: "http://womentechmakers.com", text: "WTM (Women Techmakers)"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Call for Papers
cfpTitle: "Espalhe o amor pelo JavaScript"
cfpDescription: "Uma oportunidade excelente para você mostrar do que o JavaScript é capaz, você já está por dentro das novidades do ES6, sabe como ninguém utilizar os componentes do ReactJS, programa usando JavaScript Funcional ou ainda quer explicar do que se trata esse tal de BabelJS. Siga os passos abaixo e envie sua proposta."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

#WTM JavaScript Codelab
wtmCodelabTitle: "WTM JavaScript Codelab"
trainingImage: "womentechmakers.jpg"
trainingTitle: "Instrutora"
wtmJavaScriptCodelabRows:
 - {title: "Codelab Gratuito para Mulheres", image: "1.png", details: "O WTM JavaScript Codelab tem como objetivo ensinar o básico dessa poderosa linguagem para meninas que se interessam em se aventurar no Desenvolvimento Web. As mesmas meninas que participarem desse Codelab poderão assistir as palestras da tarde do JSday e ver o quão versátil é o que elas aprenderam pela manhã.﻿"}
 - {title: "Por que JavaScript?", image: "2.png", details: "Uma das linguagens mais populares e mais utilizadas atualmente, você pode encontrá-la no seu navegador, no seu smartphone e até em sua geladeira, seguindo o conceito de Internet das Coisas.<br><br>Hoje o JavaScript está entrando num processo de evolução, inovação e padronização, com novos desenvolvimentos, como Node.js, permitindo usar o JavaScript no servidor, além de APIs HTML5 para obter dados sobre a localização de dispositivos e características geográficas e muito mais."}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false


# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
